# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=50)),
                ('item_info', models.TextField()),
                ('item_refs', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'ordering': ('noun',),
            },
        ),
        migrations.AddField(
            model_name='knowledge',
            name='item_subjects',
            field=models.ManyToManyField(blank=True, to='hally_v01.Subject'),
        ),
    ]
