# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_auto_20170528_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
