# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='message_reply',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
