# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0002_auto_20170406_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
