# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0003_post_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
