# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_site', '0006_auto_20170414_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
